### ISSUE TITLE
Conditional generation results

### ISSUE THREAD

**Issue by slothfulxtx** [lzzcd001/MeshDiffusion#10]
Hi,
thanks for your detailed introduction. Recently I try to reproduce some conditional generation results stated in Sec.5.3, but all of the generated meshes are greatly different from the ground truths. Thus I want to learn about how to reproduce the visualization results in Sec. 5.3. I've searched for many ways, but all of them don't work. Could you tell me how to reproduce the conditional generation results? The following images are the dmtet after inialization and after diffusion. 

![image](https://user-images.githubusercontent.com/37545740/235044558-ba6ce55d-933e-42b3-bc7f-036e04236230.png)

![image](https://user-images.githubusercontent.com/37545740/235044615-11cb7a4c-7f17-4e90-af8f-47f83410b2b3.png)
 

Thanks in advanced.

**Comment by lzzcd001** [comment]
Is the first figure you show the completion result? If yes, most likely you did not successfully loaded the model weight since the occluded region is still noisy. And for the second figure, the smoothing is too strong.

**Comment by slothfulxtx** [comment]
Thanks for your reply. The first figure is the single-view fitting result, which is also the input of the conditional generation process. The second figure shows the completion result after diffusion process.

**Comment by lzzcd001** [comment]
Decrease the laplacian smoothing step to 1 or 2. The current number of smoothing steps in the code works for chairs but probably being too aggressive for airplanes.
