### ISSUE TITLE
Some question about Inference.

### ISSUE THREAD

**Issue by slr1997** [lzzcd001/MeshDiffusion#15]
Where  shall I get the metadata of given DMTet dataset? 
```
data.meta_path = "PLACEHOLDER" 
data.filter_meta_path = "PLACEHOLDER" 
```
Or I should use the given dataset to run `tets_to_3dgrid.py` and `save_meta.py` for the metadata?  Or worsely, I can only get this by doing all the trainning steps?

The `$SAMPLE_PATH` should be a meshes?  If so, why the U**nconditional Generation ** and **Single-view Conditional Generation** requires different file type of `.npy` and `.obj`?The `eval.py` is just used for generate a image of one view of the object presented as meshes `$SAMPLE_PATH`?

**Comment by lzzcd001** [comment]
The inputs and outputs are the diffusion model are tetrahedral grids, not triangular meshes. The single-view conditional generation is therefore conditioned on partial tetrahedral grids. By running marching tets, you obtain triangular meshes (saved in `.obj` format) from generated tetrahedral grids (saved in `.npy').

The dataloader for diffusion model training assumes tetrahedral grids (saved as cubic grids), and `meta_path' basically is a JSON file which indicates the file locations of the saved grids. We provide datasets in the form of processed tetrahedral grids and there is no need for further data conversion steps. For details, please refer to the instructions and/or codes for data preparation.
