### ISSUE TITLE
Prepare my own dataset

### ISSUE THREAD

**Issue by FrozenSilent** [lzzcd001/MeshDiffusion#16]
Nice work! I am planning to train the network on my own data, so I followed the instructions in ReadMe to process the data, and I also obtained the `pt` file generated by DMTet. But when I wanted to load data for training, I found that the data loader did not properly handle `pt` file. The data format in the preprocessed shapenet you provided is `npy`. So I want to know if I missed any steps? Thank you!

**Comment by lzzcd001** [comment]
Hi and thank you for your interest. You need to run `tets_to_3dgrid.py` to turn the tetrahedral grids into cubic grids for diffusion model training. 

```
cd ../data/
python tets_to_3dgrid.py --resolution $RESOLUTION --root $DMTET_DICT_FOLDER --source $SOURCE_FOLDER --target grid --index 0
```

Please refer to the README for more details.

**Comment by FrozenSilent** [comment]
Thanks for your reply! Yes, I have run this command which turns those `tets` to 3D grids, saved in the `$DMTET_DICT_FOLDER/grid`. But I found that the `meta` file saved by `save_meta.py` stores the file name in the `$DMTET_DATA_PATH/tets` folder not `$DMTET_DICT_FOLDER/grid`, so the training will load the data in `$DMTET_DATA_PATH/tets`. I think this should be `$DMTET_DICT_FOLDER/grid` and I also validate this. So it would be better to correct the README file for the command `python save_meta.py --data_path $DMTET_DATA_PATH/tets --json_path $META_FILE`. Also, I found that this line in the `save_meta.py` is redundant
https://github.com/lzzcd001/MeshDiffusion/blob/021cddc02823430a238294d311cd7d4708f4e129/metadata/save_meta.py#L12
which may cause an issue when saving the `json` file.
Thank you very much again! BTW, is there any way for me to train the network in a single RTX 3090 or V100 GPU?

**Comment by lzzcd001** [comment]
Thanks for point out the typo - I have corrected the README accordingly.

Regarding your question on single-GPU training, I believe the easiest and probably the best you can do is to set a small batch size but accumulate gradients from multiple iterations (at the cost of increased training time). You can modify the number of accumulation steps by modifying `training.iter_size` in the config file.

**Comment by lzzcd001** [comment]
Thanks for point out the typo - I have corrected the README accordingly.

Regarding your question on single-GPU training, I believe the easiest thing you can do is to set a small batch size but accumulate gradients from multiple iterations (at the cost of increased training time). You can modify the number of accumulation steps by modifying training.iter_size in the config file.
