### ISSUE TITLE
No ".obj" files produced when running main_diffusion.py

### ISSUE THREAD

**Issue by anna-debug** [lzzcd001/MeshDiffusion#18]
Hello,
the code produces only .npy files, but there should be obj meshes as well. There are no errors and the command I use is this:

![image](https://github.com/lzzcd001/MeshDiffusion/assets/60916587/df7e2a21-217d-4f3a-adad-43dfe9ada162)

**Comment by lzzcd001** [comment]
Please follow the README and run `eval.py` to obtain the `.obj` file.

**Comment by shllgtca** [comment]
Perfect.

And to use the pretrained models as ckpt point, on the ckpt_path should I register the model using register_model?
