### ISSUE TITLE
NameError: name 'global_index' is not defined

### ISSUE THREAD

**Issue by shllgtca** [lzzcd001/MeshDiffusion#22]
Hi, 

Congrats for the great work!! Additionaly, I've been trying to run the Single-view Conditional Generation (over file : fit_singleview.py) but I receive the error message: NameError: name 'global_index' is not defined. 

In other files such as data/tets_to_3dgrid.py and nvdiffrec/fit_dmtets.py, the variable global_index is predefined regarding two input variables named: FLAGS.index and FLAGS.split_size. As those are not solicitated as inputs on fit_singleview.py, could you clarify how should I define it? Tks!!

**Comment by lzzcd001** [comment]
Hi and thank you for your interest in our work. I have removed `global_index` from `fit_singleview.py` as it is not used.

In `fit_dmtet.py`, `index` and `split_size` is only used for batch processing ShapeNet datasets (for instance, the 16th job process the 16th batch of meshes with a batch size of 25). It is easy to modify the code to fit a single mesh by removing the main loop and replacing the mesh path to your desired one.

**Comment by shllgtca** [comment]
Thank you so much for your super quick answer!

I read the paper a few weeks ago, so I might be missing out something, and I already apologize for taking yor time. 

But could you help me out one more time? Here it goes:

For the condionatl setting, I got able to manage the modifications that you mentioned. And it works until the sampling fucntion (l. 205) where a partial mask is assigned as a parameter. But on the function declaration although, grid_mask is assigned on get_pc_sampler, on the core function, pc_sampler is assigned and internally used.

So, I got a bit confused, can I assumed that those parameters are the same ?

Thanks a lot!

**Comment by lzzcd001** [comment]
Thanks for point it out - I forgot to rename partial_grid_mask to partial_mask.

**Comment by shllgtca** [comment]
One more question: correct me if I'm wrong, but to run the inference conditional code with a mesh not obtained from ShapeNet dataset, I've already adjusted index and split_size, but I need to run first the tets_to_3dgrid.py, then the fit_singleview.py, and next the main_diffusion on conditional setting, right?

**Comment by lzzcd001** [comment]
Here are the steps:
1) Reconstructed a partially fitted tet-grid with `fit_singleview.py`.
2) Turn it into 3D cubic grid.
3) Run diffusion model.

**Comment by shllgtca** [comment]
Hi! thanks for your answer.

Fit_single_view is asking for a file, whhich I couldn't find here or online: /aerodynamics_workshop_2k.hdr'

Do you have it? Can you uploaded it?

**Comment by shllgtca** [comment]
Perfect.

And to use the pretrained models as ckpt point, on the ckpt_path should I register the model using register_model before?
