### ISSUE TITLE
Why is the model not trained and tested jointly on multiple objects?

### ISSUE THREAD

**Issue by dqj5182** [lzzcd001/MeshDiffusion#26]
Is there any specific reason why the MeshDiffusion model is not trained on multiple objects? Is the model not generalizable to multiple objects or unseen objects?

**Comment by lzzcd001** [comment]
It is a common practice in the field to train category-specific models. Training a good category-agnostic model can require larger networks and datasets like objverse, especially for diffusion models trained on raw observation space.
