### ISSUE TITLE
Pretrained checkpoints

### ISSUE THREAD

**Issue by ruoshiliu** [lzzcd001/MeshDiffusion#3]
Hi, thank you for sharing the awesome work! I'm wondering what's the difference between the checkpoints in the google drive and the links?

![image](https://user-images.githubusercontent.com/25470644/229644450-620ec29d-f670-4fa9-9cd1-dcc2949a0301.png)

**Comment by wy1iu** [comment]
Hi, there is no difference for the models on Google drive and MPI drive. Just pick whichever link works for you.

**Comment by ruoshiliu** [comment]
Got it thank you!
