### ISSUE TITLE
what is the correspondance between $META_FILE, ShapeNetJson file

### ISSUE THREAD

**Issue by jpainam** [lzzcd001/MeshDiffusion#33]
The `$META_FILE` (provided by you) contains `6775` `dmtet 3D cubic`:
```bash
{
"/res64/chair/0000.npy",
"/res64/chair/0001.npy",
...
"/res64/chair/6774.npy"
}
```
The Train Split file `./metadata/train_split/chair_train.json` contains `4744` items  `{0, 1, 10, 22,  ... 6776}` 
This is a subset of the shapenet chair dataset.

While the Shapenet dataset contains `6777` items:

```bash
{
"/ShapeNetCore.v1/03001627/c97b5b80a24030ae70e99aac955544a0/model.obj",
....
"/ShapeNetCore.v1/03001627/8a455c7acaef577824f0493013a8318f/model.obj"
}
```

I can understand that the`dmet 3D cubic` index `0000.npy` refers to the index in `train_split/chair_train.json`. But is there a way, to know which `model.obj` generated the `dmtet 3D cubic`?

There is also   `2`dmtet missing (`6777 - 6775`)?

**Comment by lzzcd001** [comment]
Thank you for pointing out the missing data. For now please fit the missing 2 data points by yourself.

The indices correspond to the lexicographic order in file paths (for each category, respectively) -- so first sort the file paths and pick the last two to fit.
