### ISSUE TITLE
Generated Tetrahedra Representation of ShapeNet

### ISSUE THREAD

**Issue by slothfulxtx** [lzzcd001/MeshDiffusion#5]
Hi, 

Thanks for your encouraging work on mesh generation and the application of diffusion models!

When I try to train it on ShapeNet dataset following the instructions given in the README, I find that it's really time-consuming to generate the ground truth Tetrahedra representation of all models for each category. It requires about 1500 GPU hours for RTX3090 to generate the Tet ground truth on the Chair category. Will you please provide the generated tet representation of Shapenet?
  
Thanks in adance.

**Comment by lzzcd001** [comment]
Thanks for your interest in our work. We plan to release the datasets in the following week. Please stay tuned!

**Comment by slothfulxtx** [comment]
Thanks for your reply! Looking forward to your updation!

**Comment by lzzcd001** [comment]
Thank you for your patience - we have released our resolution-64 datasets. Please check our README for the download links.
