### ISSUE TITLE
Can't train the model Shapenet_dmet_dataset.py is error

### ISSUE THREAD

**Issue by wowanttoplay** [lzzcd001/MeshDiffusion#7]
Hellow，when i want to train teh model, i find in **shapenet_dmet_dataset.py** `__getitem__` function, the variable `datum` is a dict,
`'sdf:' tensor([]), 'deform' : tensor([[]]), 'deform_unmasked' : tensor()`,  but the `datum` be used like a tensor(eg : `datum[:, :1]`, `datum[1:]`), can you help sovle my problem

The error info:
`    sdf_sign = torch.sign(datum[:, :1])
TypeError: unhashable type: 'slice'`

**Comment by lzzcd001** [comment]
Thanks for pointing out. Please run `tet_to_3dgrid.py` in `data` folder to convert the dataset of tetrahedral grids (stored as dicts) into a dataset of 3D cubic grids (stored as tensors). We will update the README accordingly.
