### ISSUE TITLE
Creat a list of paths

### ISSUE THREAD

**Issue by TFNTF** [lzzcd001/MeshDiffusion#8]
Hello~It is really an impressive work.

Could you please instruct me that how to create a list of paths of all ground-truth meshes and store them as a json file under shapenet_json. For example, I've downloaded ShapeNetCore.

Thanks.

**Comment by lzzcd001** [comment]
For ShapeNet v2

```
import json
instance_names = os.listdir(shapenet_category_path)
mesh_files = [os.path.join(shapenet_category_path, instance_name, 'models/model_normalized.obj') for instance_name in instance_names]
json.dump(mesh_files, open('json_file.json'))
```

**Comment by jpainam** [comment]
What you do mean by `normalized_mesh.obj`? is the `res-64`,?
